version: "3"
services:
  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: oauth
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  elite2:
    image: quay.io/hmpps/prison-api:latest
    container_name: elite2
    depends_on:
      - oauth
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  offender-case-notes:
    image: quay.io/hmpps/offender-case-notes:latest
    container_name: offender-case-notes
    depends_on:
      - elite2
    ports:
      - "8083:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=stdout,localstack
      - ELITE2_API_BASE_URL=http://elite2:8080
      - SQS_ENDPOINT_URL=http://localstack:4576
