apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whereabouts-api
  labels:
    app: whereabouts-api
spec:
  replicas: 2
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: whereabouts-api
  template:
    metadata:
      labels:
        app: whereabouts-api
    spec:
      containers:
        - name: whereabouts-api
          image: 926803513772.dkr.ecr.eu-west-2.amazonaws.com/omic/whereabouts-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 360m
              memory: "1024Mi"
            requests:
              cpu: 180m
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 70
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: SERVER_PORT
              value: "9090"
            - name: SPRING_PROFILES_ACTIVE
              value: "postgres"
            - name: JWT_PUBLIC_KEY
              value: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBemN4N1lidzJCQVd2N1NzRUlVR1ANCml5SlNJRGd0cUJ4MTlUd203dUkzVFg1elJjclpsVXhjRW1QSkdVZ3krRDJKSWhWbHFtZXF3R1YyQ05PcVpCZ0cNCmo4ZUpHQTU5aUlUemU4ZG1SSk5JYzdsNmxESmc5RE5KVk9pTHFVbFpGRENJcXplSTYzb3E2dWhjY2c1RFBpVE4NCnFPR1pjOHVwTit3NWRack52KzJHTGd4SzJwZXRNVS9CaFllV2YzS3ZZSU8xNnYxdXZuRk9HTzEzSG9XdTVCdGQNClN0L1RnY2xGaFZMRWRHdzdYYmlZSG5OWklkaHdhTlFpWWdtWG1qWlZkTXlDUERNbzEwTGtWMXAzVXkxNXBNTXgNClVwc2xKYU8wNlZIYXJtY3ZWYzNleHg5NlpHTjE2T2U4ZWZoeG5Rdmhzd0ZrbXlYT25sSForNDI1MnJHcHlKTG8NCmx3SURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0="
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: whereabouts-api-rds-dev
                  key: database_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: whereabouts-api-rds-dev
                  key: database_username
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: whereabouts-api-rds-dev
                  key: rds_instance_endpoint
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: whereabouts-api-rds-dev
                  key: database_name
